pipelines:
  - name: "your_pipeline_name"                        # Required, specify a name for pipeline on Launchpad              
    url: "your_pipeline_url"                          # Required, specify a pipeline URL
    workspace: "$ORGANIZATION_NAME/$WORKSPACE_NAME"   # Required, specify a workspace
    description: "your_pipeline_description"          # Optional, specify a pipeline description
    compute-env: "$COMPUTE_ENV_PREFIX_plain_s3"       # Required, selects for Fusion CE created in earlier step
    profile: "$PIPELINE_PROFILE"                      # Optional, specify a test profile
    revision: "your_pipeline_revision"                # Required, specify a pipeline revision
    config: "./plainS3.config"                       # Required, specify a config file with process resource labels for costs
    # pre-run: "./pre-run.sh"                           # Optional, specify a pre-run script                
    # params-file: "./params.yaml"                      # Optional, specify a pipeline params file
    params:                                           # Optional, specify params inline
      input: 's3://your-bucket/input/samplesheet.csv'
    labels: "fusion_benchmark,plains3"                # Optional, specify pipeline labels to organize runs